export const NAME = 'app'

export const ADD_NEW_RAMIFICATION = `${NAME}/NEW_RAMIFICATION`
export const ADD_NEW_RESPONSABLE = `${NAME}/NEW_RESPONSABLE`
export const ADD_NEW_MEMBER = `${NAME}/NEW_MEMBER`
export const ADD_RESPONSABLE_RAMIFICATION = `${NAME}/NEW_RESPONSABLE_RAMIFICATION`
export const ADD_MEMBER_RAMIFICATION = `${NAME}/NEW_MEMBER_RAMIFICATION`
export const DELETE_MEMBER_RAMIFICATION = `${NAME}/DELETE_MEMBER_RAMIFICATION`
export const DELETE_RESPONSABLE_RAMIFICATION = `${NAME}/DELETE_RESPONSABLE_RAMIFICATION`
